# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.box = "ubuntu-18.04-virtualbox.box"
    virtualbox.ssh.username = "vagrant"
    virtualbox.ssh.password = "vagrant"
  end

end
